- name: Deploy Dev to Prod
  uses: gagoar/invoke-aws-lambda@master
  with:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      FunctionName: replace-s3-contents-with-other-s3-contents
      Payload: '{ "sourceBucketName": "dev.jamesworden.com", "targetBucketName": "www.jamesworden.com" }'
